"use client";
import {useEffect,useMemo,useState} from "react";import{useParams,useRouter}from"next/navigation";import{apiFetch,money}from"@/lib/api";
export default function Product(){const{slug}=useParams<{slug:string}>();const router=useRouter();const[p,setP]=useState<any>(null);const[color,setColor]=useState<any>(null);const[variant,setVariant]=useState<any>(null);const[main,setMain]=useState("");const[msg,setMsg]=useState("");useEffect(()=>{fetch(`/backend-api/products/${slug}/`,{cache:"no-store"}).then(r=>r.json()).then(x=>{setP(x);setMain(x.image||x.gallery?.[0]||"");const first=x.variants?.find((v:any)=>v.available)||x.variants?.[0];if(first){setColor(first.color);setVariant(first)}})},[slug]);const colors=useMemo(()=>{const map=new Map();p?.variants?.forEach((v:any)=>map.set(v.color.id,v.color));return [...map.values()]},[p]);const sizes=useMemo(()=>p?.variants?.filter((v:any)=>color&&v.color.id===color.id)||[],[p,color]);if(!p)return <div className="empty container">Loading product…</div>;async function add(){if(!variant)return;try{await apiFetch("/cart/add/",{method:"POST",body:JSON.stringify({variantId:variant.id,quantity:1})});window.dispatchEvent(new Event("lv:cart-changed"));setMsg("Added to cart.")}catch(e:any){setMsg(e.message)}}async function wish(){try{await apiFetch(`/wishlist/toggle/${p.id}/`,{method:"POST",body:"{}"});window.dispatchEvent(new Event("lv:wishlist-changed"));setP({...p,wishlisted:!p.wishlisted})}catch(e:any){if(e.message.includes("Authentication"))router.push(`/login?next=/product/${slug}`);else setMsg(e.message)}}return <main className="product-page">
 <div className="gallery">{[main,...(p.gallery||[]).filter((x:string)=>x!==main)].slice(0,4).map((img:string,i:number)=><div className="gallery-cell" key={i}>{img&&<img src={img} alt={`${p.name} ${i+1}`}/>}</div>)}</div>
 <aside className="detail-panel"><div className="detail-sticky"><div className="eyebrow">{p.category?.name||"LE VAURÉ"}</div><h1>{p.name}</h1><p className="detail-desc">{p.description}</p><div className="detail-price">{money(variant?.price||p.price)}</div>
 {!!colors.length&&<div className="option"><div className="option-head"><span>COLOR: {color?.name}</span></div><div className="swatches">{colors.map((c:any)=><button aria-label={c.name} key={c.id} className={`swatch ${color?.id===c.id?"active":""}`} onClick={()=>{setColor(c);const next=p.variants.find((v:any)=>v.color.id===c.id&&v.available)||p.variants.find((v:any)=>v.color.id===c.id);setVariant(next);if(next?.image)setMain(next.image)}}><span style={{"--swatch":c.hex} as any}/></button>)}</div></div>}
 {!!sizes.length&&<div className="option"><div className="option-head"><span>SIZE: {variant?.size?.name||"Select"}</span><span>SIZE GUIDE</span></div><div className="sizes">{sizes.map((v:any)=><button key={v.id} disabled={!v.available} className={`size ${variant?.id===v.id?"active":""}`} onClick={()=>{setVariant(v);if(v.image)setMain(v.image)}}>{v.size.name}</button>)}</div></div>}
 <div className="stock">{variant?variant.available?`${variant.stock} AVAILABLE`:"SOLD OUT":"SELECT AN OPTION"}</div><div className="buy-row"><button className="buy" disabled={!variant?.available} onClick={add}>ADD TO CART →</button><button className="wish" onClick={wish}>{p.wishlisted?"♥ REMOVE FROM WISHLIST":"♡ ADD TO WISHLIST"}</button></div>{msg&&<p className="success">{msg}</p>}
 <div className="accordion"><details open><summary>PRODUCT DETAILS</summary><p>{p.description}</p></details><details><summary>DELIVERY & RETURNS</summary><p>Fast delivery across Armenia. Returns accepted within 14 days according to store policy.</p></details><details><summary>CARE</summary><p>Follow the product care label and treat premium materials gently.</p></details></div></div></aside>
 </main>}
