"use client";
import Link from "next/link";import {useEffect,useState} from "react";import ProductCard from "@/components/ProductCard";
export default function Home(){const[d,setD]=useState<any>(null);useEffect(()=>{fetch("/backend-api/home/",{cache:"no-store"}).then(r=>r.json()).then(setD).catch(()=>{})},[]);if(!d)return <div className="empty container">Loading LE VAURÃ‰â€¦</div>;const hero=d.heroes?.[0];return <main>
 {hero&&<section className="hero" style={{backgroundImage:`url(${hero.image})`}}><div className="hero-inner"><div className="hero-copy"><div className="eyebrow" style={{color:"white"}}>{hero.eyebrow}</div><h1>{hero.title}</h1><p>{hero.subtitle}</p><Link className="btn" href={hero.buttonUrl||"/shop"}>{hero.buttonLabel||"SHOP NOW"} â†’</Link></div></div></section>}
 <div className="benefits"><div className="benefit"><strong>FAST DELIVERY</strong><small>All over Armenia</small></div><div className="benefit"><strong>SECURE CHECKOUT</strong><small>Your data is protected</small></div><div className="benefit"><strong>EASY RETURNS</strong><small>Within 14 days</small></div><div className="benefit"><strong>PREMIUM QUALITY</strong><small>Designed to last</small></div></div>
 <section className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">CURATED FOR YOU</div><h2>SHOP T-SHIRTS</h2></div><Link href="/shop">VIEW ALL â†’</Link></div><div className="grid">{d.featuredProducts?.map((p:any)=><ProductCard key={p.id} p={p}/>)}</div></div></section>
 {d.promos?.[0]&&<section className="promo" style={{backgroundImage:`url(${d.promos[0].image})`}}><div className="container content"><div className="eyebrow" style={{color:"white"}}>SPECIAL OFFER</div><h2>{d.promos[0].title}</h2><p>{d.promos[0].subtitle}</p><Link className="btn" href={d.promos[0].buttonUrl||"/shop"}>{d.promos[0].buttonLabel||"SHOP NOW"} â†’</Link></div></section>}
 {!!d.collections?.length&&<section className="section"><div className="container"><div className="section-head"><h2>EXPLORE COLLECTIONS</h2><Link href="/collections">VIEW ALL â†’</Link></div><div className="collections">{d.collections.map((c:any)=><Link key={c.slug} href={`/collections/${c.slug}`} className="collection-card" style={{backgroundImage:`url(${c.image})`}}><div><h3>{c.name}</h3><span>SHOP NOW â†’</span></div></Link>)}</div></div></section>}
 {d.editorials?.[0]&&<section className="editorial"><div className="editorial-image" style={{backgroundImage:`url(${d.editorials[0].image})`}}/><div className="editorial-copy"><div className="eyebrow">{d.editorials[0].eyebrow}</div><h2>{d.editorials[0].title}</h2><p>{d.editorials[0].body}</p>{d.editorials[0].buttonUrl&&<Link className="btn secondary" href={d.editorials[0].buttonUrl}>{d.editorials[0].buttonLabel||"DISCOVER"} â†’</Link>}</div></section>}
 {!!d.journal?.length&&<section className="section"><div className="container"><div className="section-head"><h2>JOURNAL</h2><Link href="/journal">SEE ALL â†’</Link></div><div className="journal-grid">{d.journal.slice(0,3).map((j:any)=><Link className="journal-card" href={`/journal/${j.slug}`} key={j.slug}><img src={j.coverImage} alt={j.title}/><h3>{j.title}</h3><p>{j.excerpt}</p></Link>)}</div></div></section>}
 </main>}

