from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0011_create_site_access_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductColor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
                ("hex_code", models.CharField(default="#111111", max_length=7)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.CreateModel(
            name="ProductSize",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20, unique=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("brand_name", models.CharField(default="LE VAURÉ", max_length=80)),
                ("brand_tagline", models.CharField(default="CLOTHING WITH A PURPOSE", max_length=180)),
                ("primary_color", models.CharField(default="#0B2F26", max_length=7)),
                ("accent_color", models.CharField(default="#C9A96E", max_length=7)),
                ("announcement", models.CharField(default="FREE DELIVERY ALL OVER ARMENIA ON ORDERS OVER 12,000 ֏", max_length=220)),
                ("support_email", models.EmailField(blank=True, default="", max_length=254)),
                ("support_phone", models.CharField(blank=True, default="", max_length=40)),
                ("instagram_url", models.URLField(blank=True, default="")),
                ("facebook_url", models.URLField(blank=True, default="")),
                ("tiktok_url", models.URLField(blank=True, default="")),
                ("footer_note", models.CharField(blank=True, default="Made with ♥ in Armenia", max_length=220)),
                ("default_shipping_text", models.CharField(default="Fast delivery across Armenia", max_length=220)),
                ("default_returns_text", models.CharField(default="Easy returns within 14 days", max_length=220)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "Storefront settings", "verbose_name_plural": "Storefront settings"},
        ),
        migrations.CreateModel(
            name="NavigationItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=80)),
                ("url", models.CharField(max_length=220)),
                ("location", models.CharField(choices=[("header", "Header"), ("footer_shop", "Footer / Shop"), ("footer_help", "Footer / Help"), ("footer_company", "Footer / Company")], default="header", max_length=20)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("open_new_tab", models.BooleanField(default=False)),
            ],
            options={"ordering": ["location", "sort_order", "id"]},
        ),
        migrations.CreateModel(
            name="HomeHeroSlide",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("eyebrow", models.CharField(blank=True, default="NEW COLLECTION", max_length=80)),
                ("title", models.CharField(max_length=180)),
                ("subtitle", models.TextField(blank=True, default="")),
                ("image", models.ImageField(upload_to="home/heroes/")),
                ("mobile_image", models.ImageField(blank=True, null=True, upload_to="home/heroes/mobile/")),
                ("button_label", models.CharField(default="SHOP NOW", max_length=60)),
                ("button_url", models.CharField(default="/shop", max_length=220)),
                ("text_position", models.CharField(choices=[("left", "Left"), ("center", "Center"), ("right", "Right")], default="left", max_length=20)),
                ("overlay_opacity", models.PositiveSmallIntegerField(default=18, help_text="0-80")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
            ],
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.CreateModel(
            name="PromoBanner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=180)),
                ("subtitle", models.TextField(blank=True, default="")),
                ("image", models.ImageField(upload_to="home/promos/")),
                ("button_label", models.CharField(blank=True, default="SHOP NOW", max_length=60)),
                ("button_url", models.CharField(blank=True, default="/shop", max_length=220)),
                ("placement", models.CharField(choices=[("home_mid", "Home / middle"), ("home_bottom", "Home / bottom"), ("shop", "Shop"), ("collection", "Collection")], default="home_mid", max_length=30)),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["placement", "sort_order", "id"]},
        ),
        migrations.CreateModel(
            name="EditorialBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=180)),
                ("eyebrow", models.CharField(blank=True, default="", max_length=80)),
                ("body", models.TextField(blank=True, default="")),
                ("image", models.ImageField(upload_to="editorial/")),
                ("button_label", models.CharField(blank=True, default="", max_length=60)),
                ("button_url", models.CharField(blank=True, default="", max_length=220)),
                ("placement", models.CharField(choices=[("home", "Home"), ("about", "About"), ("shop", "Shop")], default="home", max_length=30)),
                ("image_side", models.CharField(choices=[("left", "Left"), ("right", "Right")], default="left", max_length=10)),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["placement", "sort_order", "id"]},
        ),
        migrations.CreateModel(
            name="JournalPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(max_length=190, unique=True)),
                ("excerpt", models.TextField(blank=True, default="")),
                ("body", models.TextField()),
                ("cover_image", models.ImageField(upload_to="journal/")),
                ("author_name", models.CharField(default="LE VAURÉ", max_length=100)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("featured", models.BooleanField(default=False)),
            ],
            options={"ordering": ["-published_at", "-id"]},
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sku", models.CharField(blank=True, db_index=True, default="", max_length=80)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("price", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="products/variants/")),
                ("active", models.BooleanField(default=True)),
                ("color", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="variants", to="shop.productcolor")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="variants", to="shop.product")),
                ("size", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="variants", to="shop.productsize")),
            ],
            options={"ordering": ["color__sort_order", "size__sort_order", "id"]},
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(fields=("product", "color", "size"), name="unique_product_color_size"),
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("subtitle", models.CharField(blank=True, default="", max_length=220)),
                ("description", models.TextField(blank=True, default="")),
                ("image", models.ImageField(blank=True, null=True, upload_to="collections/")),
                ("featured", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("products", models.ManyToManyField(blank=True, related_name="collections", to="shop.product")),
            ],
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.CreateModel(
            name="CustomerAddress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(default="Home", max_length=40)),
                ("full_name", models.CharField(max_length=160)),
                ("phone", models.CharField(max_length=50)),
                ("country", models.CharField(default="Armenia", max_length=80)),
                ("region", models.CharField(blank=True, default="", max_length=120)),
                ("city", models.CharField(max_length=120)),
                ("street", models.CharField(max_length=255)),
                ("apartment", models.CharField(blank=True, default="", max_length=120)),
                ("postal_code", models.CharField(blank=True, default="", max_length=40)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="addresses", to="auth.user")),
            ],
            options={"ordering": ["-is_default", "-created_at"]},
        ),
        migrations.CreateModel(
            name="PasswordResetCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code_hash", models.CharField(max_length=200)),
                ("expires_at", models.DateTimeField()),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_sent_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="password_reset_code", to="auth.user")),
            ],
        ),
        migrations.CreateModel(
            name="OrderVerificationCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code_hash", models.CharField(max_length=200)),
                ("expires_at", models.DateTimeField()),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("order", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="verification", to="shop.order")),
            ],
        ),
        migrations.AddField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="order_items", to="shop.productvariant"),
        ),
        migrations.AddField(model_name="orderitem", name="color_name", field=models.CharField(blank=True, default="", max_length=80)),
        migrations.AddField(model_name="orderitem", name="size_name", field=models.CharField(blank=True, default="", max_length=40)),
    ]
