# Generated by Django 5.2.17 on 2026-09-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_full_page_designer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='body_size',
            field=models.PositiveIntegerField(default=13, help_text='Body text size (px)'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='content_width',
            field=models.PositiveSmallIntegerField(default=45, help_text='Text block width: 20-100%'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='content_x',
            field=models.PositiveSmallIntegerField(default=8, help_text='Text horizontal position: 0-100'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='content_y',
            field=models.PositiveSmallIntegerField(default=72, help_text='Text vertical position: 0-100'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='desktop_height',
            field=models.PositiveIntegerField(default=620, help_text='Banner height on desktop (px)'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='image_x',
            field=models.PositiveSmallIntegerField(default=50, help_text='Image horizontal position: 0-100'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='image_y',
            field=models.PositiveSmallIntegerField(default=50, help_text='Image vertical position: 0-100'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='image_zoom',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Image zoom: 1.00-3.00', max_digits=4),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='mobile_height',
            field=models.PositiveIntegerField(default=420, help_text='Banner height on mobile (px)'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='mobile_title_size',
            field=models.PositiveIntegerField(default=34, help_text='Mobile title size (px)'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='overlay_opacity',
            field=models.PositiveSmallIntegerField(default=35, help_text='Overlay opacity: 0-100'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='text_align',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='title_size',
            field=models.PositiveIntegerField(default=48, help_text='Desktop title size (px)'),
        ),
    ]
