# Generated by Django 5.2.17 on 2026-09-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_pagesection_body_size_pagesection_content_width_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='main', max_length=40, unique=True)),
                ('draft', models.JSONField(blank=True, default=dict)),
                ('published', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Site design',
                'verbose_name_plural': 'Site design',
            },
        ),
    ]
